version: "3.5"
services:
  worker-0000:
    build: ./worker_files/
    volumes: 
      - ./worker_files/:/usr/src/app:z
      - ./common/utils/:/usr/src/app/utils:z
      - ./common/base_stream/:/usr/src/app/base_stream:z
    environment: 
      - PYTHONUNBUFFERED=1
      - WORKER_ID=0000
    depends_on: 
      - broker
    env_file: 
      - hosts.env
      - constants.env
    networks: 
      - network_test_bed

  worker-0001:
    build: ./worker_files/
    volumes: 
      - ./worker_files/:/usr/src/app:z
      - ./common/utils/:/usr/src/app/utils:z
      - ./common/base_stream/:/usr/src/app/base_stream:z
    environment: 
      - PYTHONUNBUFFERED=1
      - WORKER_ID=0001
    depends_on: 
      - broker
    env_file: 
      - hosts.env
      - constants.env
    networks: 
      - network_test_bed

  worker-0002:
    build: ./worker_files/
    volumes: 
      - ./worker_files/:/usr/src/app:z
      - ./common/utils/:/usr/src/app/utils:z
      - ./common/base_stream/:/usr/src/app/base_stream:z
    environment: 
      - PYTHONUNBUFFERED=1
      - WORKER_ID=0002
    depends_on: 
      - broker
    env_file: 
      - hosts.env
      - constants.env
    networks: 
      - network_test_bed

  broker:
    build: ./broker_files/
    ports:
      - "6000:6000"
      - "7000:7000"
      - "8000:8000"
      - "9000:9000"
    volumes:
      - ./broker_files:/usr/src/app:z
      - ./common/utils/:/usr/src/app/utils:z
      - ./common/base_stream/:/usr/src/app/base_stream:z
    environment: 
      - PYTHONUNBUFFERED=1
    env_file: 
      - hosts.env
      - constants.env
    networks: 
      - network_test_bed

  influxdb:
    image: influxdb:1.7.3-alpine
    volumes:
        - ./data/influxdb:/var/lib/influxdb:z
    ports:
      - "8086:8086"
    environment: 
      - PYTHONBUFFERED=1
    logging:
      driver: none

networks:
  network_test_bed:

