version: "2.2"
services:
  worker_000:
    build: ./worker_files/
    volumes: 
      - ./worker_files/:/usr/src/app
    environment: 
      - PYTHONUNBUFFERED=1
      - WORKER_ID=0000
    depends_on: 
      - broker
    env_file: 
      - hosts.env
      - constants.env

  broker:
    build: ./broker_files/
    ports:
      - "6000:6000"
      - "7000:7000"
      - "9999:9999"
    volumes:
      - ./broker_files:/usr/src/app
    environment: 
      - PYTHONUNBUFFERED=1
    env_file: 
      - hosts.env
      - constants.env

  influxdb:
    image: influxdb:1.7.3-alpine
    volumes:
      - ./data/influxdb:/var/lib/influxdb
    ports:
      - "8086:8086"
    environment: 
      - PYTHONBUFFERED=1
    logging:
      driver: none